### PR TITLE
Make the package build with Stack LTS 6.4

### PR DESCRIPTION
**Pull request by gabebw**
LTS 6.4 is the latest version.

```
persistent-database-url/src/Database/Persist/URL.hs:33:40:
    Not in scope: ‘uriAuthority’
    Perhaps you meant data constructor ‘Authority’ (imported from URI.ByteString)
```

Unfortunately, it fails to build on LTS 5.11:

```
Module ‘URI.ByteString’ does not export ‘URIRef(..)’
```

### CODE REVIEW

**Comment by gabebw** [comment]
I don't know how to make this package build with both LTS 5.11 and 6.3.

**Comment by jferris** [comment]
Some ideas:
- Use preprocessor statements to check the uri-bytestring version?
- Release one version compatible with LTS 5.x and one version compatible with LTS 6.x?

**Comment by gabebw** [comment]
Ready for re-review.

I confirmed that it works on LTS 5.11 and LTS 6.3 by doing the following for both versions:
- Changing the version in `stack.yaml`
- Running `rm -rf .stack-work && stack build`

Also: I thought I'd need `other-extensions: CPP` in the cabalfile, but it works fine with just the `LANGUAGE` directive.

**Comment by gabebw** [comment]
I believe CI is failing because the Launchpad is timing out: https://launchpad.net/~hvr/+archive/ubuntu/ghc

I'll rebuild later.

**Comment by gabebw** [comment]
The build passed!

**Comment by jferris** [comment]
This looks good to me.

Note, we probably want to reference the package via a Git URL in `stack.yaml` instead of releasing a new version, because we still haven't worked out the best types to make this easy to use.

**Comment by gabebw** [comment]
> Note, we probably want to reference the package via a Git URL in stack.yaml instead of releasing a new version

You mean when using this package, right, and that there are no Git-URL-related changes required to the `stack.yaml` in this project?

**Comment by jferris** [comment]
> You mean when using this package, right?

Sorry, I wasn't very clear. I was trying to say that:
- Although it builds on more versions of Stack, this doesn't fix the usability issues we have
- I'm not sure it's worth releasing a new version of this package now

**Comment by gabebw** [comment]
Ah, yeah, agreed. It sounds like those are good issues to open on this repo. (Also, I don't know how to release a new version, so no worries from me on that front.)
